services:
#  nextuni.api:
#    image: ${DOCKER_REGISTRY-}nextuniapi
#    container_name: NextUni.Api
#    build:
#      context: .
#      dockerfile: src/API/NextUni.Api/Dockerfile
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - 5623:8080
#      - 7125:8081
#    depends_on:
#      - nextuni.identity
#
  nextuni.database:
    image: postgres:latest
    container_name: NextUni.Database
    environment:
      - POSTGRES_DB=nextuni
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nextuni.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: NextUni.Identity
    command: start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://nextuni.database:5432/nextuni
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - nextuni.database
    volumes:
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080
  
  nextuni.seq:
    image: datalust/seq:latest
    container_name: NextUni.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  nextuni.redis:
    image: redis:latest
    container_name: NextUni.Redis
    restart: always
    ports:
      - 6379:6379
volumes:
  pg_data:
