services:
  #  nextuni.api:
  #    image: ${DOCKER_REGISTRY-}nextuniapi
  #    container_name: NextUni.Api
  #    build:
  #      context: .
  #      dockerfile: src/API/NextUni.Api/Dockerfile
  #    environment:
  #      - ASPNETCORE_ENVIRONMENT=Development
  #    ports:
  #      - 5623:8080
  #      - 7125:8081
  #    depends_on:
  #      - nextuni.identity
  #
  nextuni.database:
    image: postgres:latest
    container_name: NextUni.Database
    environment:
      - POSTGRES_DB=nextuni
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nextuni.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: NextUni.Identity
    command: start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://nextuni.database:5432/nextuni
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_SCHEMA_UPDATE=true
    depends_on:
      - nextuni.database
    volumes:
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080
  
  nextuni.seq:
    image: datalust/seq:latest
    container_name: NextUni.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - 5341:5341
      - 8081:80

  nextuni.redis:
    image: redis:latest
    container_name: NextUni.Redis
    restart: always
    ports:
      - 6379:6379
  
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_data:/qdrant/storage
configs:
  qdrant_config:
    content: |
      log_level: INFO
volumes:
  pg_data:
  qdrant_data:
