<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NextUni.Common.Api\NextUni.Common.Api.csproj" />
        <ProjectReference Include="..\NextUni.Common.Application\NextUni.Common.Application.csproj" />
        <ProjectReference Include="..\NextUni.Common.Domain\NextUni.Common.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
        <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
        <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="9.0.0" />
        <PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
        <PackageReference Include="MassTransit" Version="8.4.1" />
        <PackageReference Include="MassTransit.Redis" Version="8.4.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.16" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.5" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

</Project>
