<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\NextUni.Common.Application\NextUni.Common.Application.csproj" />
      <ProjectReference Include="..\NextUni.Modules.Chatbot.Domain\NextUni.Modules.Chatbot.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.17" />
      <PackageReference Include="Microsoft.Extensions.AI" Version="9.6.0" />
      <PackageReference Include="Microsoft.Extensions.AI.Abstractions" Version="9.6.0" />
      <PackageReference Include="Qdrant.Client" Version="1.14.1" />
    </ItemGroup>

</Project>
