// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextUni.Modules.Academic.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NextUni.Modules.Academic.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AcademicDbContext))]
    partial class AcademicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("academic")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NextUni.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "academic");
                });

            modelBuilder.Entity("NextUni.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "academic");
                });

            modelBuilder.Entity("NextUni.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "academic");
                });

            modelBuilder.Entity("NextUni.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "academic");
                });

            modelBuilder.Entity("NextUni.Modules.Academic.Domain.IntroductionBlogs.IntroductionBlog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<byte>("IntroductionType")
                        .HasColumnType("smallint")
                        .HasColumnName("introduction_type");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_introduction_blogs");

                    b.ToTable("introduction_blogs", "academic");
                });

            modelBuilder.Entity("NextUni.Modules.Academic.Domain.Majors.AdmissionScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("ExamScore")
                        .HasColumnType("real")
                        .HasColumnName("exam_score");

                    b.Property<float>("GpaScore")
                        .HasColumnType("real")
                        .HasColumnName("gpa_score");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid")
                        .HasColumnName("major_id");

                    b.Property<DateOnly>("Year")
                        .HasColumnType("date")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_admission_scores");

                    b.HasIndex("MajorId", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_admission_scores_major_id_year");

                    b.ToTable("admission_scores", "academic");
                });

            modelBuilder.Entity("NextUni.Modules.Academic.Domain.Majors.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.HasKey("Id")
                        .HasName("pk_majors");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_majors_university_id");

                    b.HasIndex("Code", "UniversityId")
                        .IsUnique()
                        .HasDatabaseName("ix_majors_code_university_id");

                    b.ToTable("majors", "academic");
                });

            modelBuilder.Entity("NextUni.Modules.Academic.Domain.Majors.MajorSubjectGroupByYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid")
                        .HasColumnName("major_id");

                    b.Property<Guid>("SubjectGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_group_id");

                    b.Property<DateOnly>("Year")
                        .HasColumnType("date")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_major_subject_group_by_year");

                    b.HasIndex("MajorId")
                        .HasDatabaseName("ix_major_subject_group_by_year_major_id");

                    b.HasIndex("SubjectGroupId")
                        .HasDatabaseName("ix_major_subject_group_by_year_subject_group_id");

                    b.ToTable("major_subject_group_by_year", "academic");
                });

            modelBuilder.Entity("NextUni.Modules.Academic.Domain.Subjects.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_subjects");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_subjects_name");

                    b.ToTable("subjects", "academic");
                });

            modelBuilder.Entity("NextUni.Modules.Academic.Domain.Subjects.SubjectGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_subject_groups");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_subject_groups_code");

                    b.ToTable("subject_groups", "academic");
                });

            modelBuilder.Entity("NextUni.Modules.Academic.Domain.Universities.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FacebookUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("facebook_url");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<byte>("Region")
                        .HasColumnType("smallint")
                        .HasColumnName("region");

                    b.Property<byte>("UniversityType")
                        .HasColumnType("smallint")
                        .HasColumnName("university_type");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_universities");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_universities_code");

                    b.ToTable("universities", "academic");
                });

            modelBuilder.Entity("SubjectSubjectGroup", b =>
                {
                    b.Property<Guid>("SubjectGroupsId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_groups_id");

                    b.Property<Guid>("SubjectsId")
                        .HasColumnType("uuid")
                        .HasColumnName("subjects_id");

                    b.HasKey("SubjectGroupsId", "SubjectsId")
                        .HasName("pk_subject_subject_group");

                    b.HasIndex("SubjectsId")
                        .HasDatabaseName("ix_subject_subject_group_subjects_id");

                    b.ToTable("subject_subject_group", "academic");
                });

            modelBuilder.Entity("NextUni.Modules.Academic.Domain.Majors.AdmissionScore", b =>
                {
                    b.HasOne("NextUni.Modules.Academic.Domain.Majors.Major", "Major")
                        .WithMany("AdmissionScore")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admission_scores_majors_major_id");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("NextUni.Modules.Academic.Domain.Majors.Major", b =>
                {
                    b.HasOne("NextUni.Modules.Academic.Domain.Universities.University", "University")
                        .WithMany("Majors")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_majors_universities_university_id");

                    b.Navigation("University");
                });

            modelBuilder.Entity("NextUni.Modules.Academic.Domain.Majors.MajorSubjectGroupByYear", b =>
                {
                    b.HasOne("NextUni.Modules.Academic.Domain.Majors.Major", null)
                        .WithMany("SubjectGroupsByYear")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_major_subject_group_by_year_majors_major_id");

                    b.HasOne("NextUni.Modules.Academic.Domain.Subjects.SubjectGroup", null)
                        .WithMany("MajorSubjectGroupByYears")
                        .HasForeignKey("SubjectGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_major_subject_group_by_year_subject_groups_subject_group_id");
                });

            modelBuilder.Entity("SubjectSubjectGroup", b =>
                {
                    b.HasOne("NextUni.Modules.Academic.Domain.Subjects.SubjectGroup", null)
                        .WithMany()
                        .HasForeignKey("SubjectGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subject_subject_group_subject_groups_subject_groups_id");

                    b.HasOne("NextUni.Modules.Academic.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subject_subject_group_subjects_subjects_id");
                });

            modelBuilder.Entity("NextUni.Modules.Academic.Domain.Majors.Major", b =>
                {
                    b.Navigation("AdmissionScore");

                    b.Navigation("SubjectGroupsByYear");
                });

            modelBuilder.Entity("NextUni.Modules.Academic.Domain.Subjects.SubjectGroup", b =>
                {
                    b.Navigation("MajorSubjectGroupByYears");
                });

            modelBuilder.Entity("NextUni.Modules.Academic.Domain.Universities.University", b =>
                {
                    b.Navigation("Majors");
                });
#pragma warning restore 612, 618
        }
    }
}
