<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\NextUni.Common.Infrastructure\NextUni.Common.Infrastructure.csproj" />
      <ProjectReference Include="..\NextUni.Modules.Contents.Api\NextUni.Modules.Contents.Api.csproj" />
    </ItemGroup>

</Project>
