<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\NextUni.Common.Api\NextUni.Common.Api.csproj" />
      <ProjectReference Include="..\..\Users\NextUni.Modules.Users.IntegrationEvents\NextUni.Modules.Users.IntegrationEvents.csproj" />
      <ProjectReference Include="..\NextUni.Modules.Events.Application\NextUni.Modules.Events.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="EventRegistrations\" />
    </ItemGroup>

</Project>
