<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\NextUni.Common.Application\NextUni.Common.Application.csproj" />
      <ProjectReference Include="..\NextUni.Modules.Academic.Domain\NextUni.Modules.Academic.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="IntroductionBlogs\CreateMajorIntroductionBlog\" />
      <Folder Include="Universities\GetUniversities\" />
      <Folder Include="Universities\UpdateUniversity\" />
    </ItemGroup>

</Project>
